[build]
  command = "npm run build && npm install --arch=x64 --platform=linux @sparticuz/chromium"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium", "puppeteer-core"]

  [functions.timeout]
    duration = 30

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "21"
